<?php return array(
    'Home',
    'Tournament',
    'About Us',
    'ABOUT',
    'Blog',
    'Blog Details',
    'FAQS',
    'Contact Us',
    'Terms & Conditions',
    'Privacy & Policy',
    'Policy',
    'Sign In',
    'Sign Up',
    'Dashboard',
    'Logout',
    'Balance',
    'Copyrights',
    'All rights reserved.',
    'My Prediction',
    'Operations',
    'Deposit Money',
    'Withdraw Money',
    'Money Transfer',
    'My Log',
    'Transaction Log',
    'Deposit Log',
    'Withdraw Log',
    'Profile Settings',
    'Password Settings',
    'Name',
    'Email',
    'Subject',
    'Message',
    'PREDICT NOW',
    'COMPLETE',
    'No question available',
    'Total User',
    'Total Prediction',
    'Total Gateways',
    'Withdraw Method',
    'Leader Board',
    'Weekly',
    'All Time',
    'Prediction',
    'Amount',
    'User',
    'Read More',
    'We Accept',
    'We Are Here To Help You Needs',
    'Popular Posts',
    'Prediction Now',
    'MINIMUM PREDICT AMOUNT',
    'IF YOU WIN',
    'RETURN AMOUNT',
    'Charge Apply From This Amount',
    'Maximum',
    'Predict in this Option',
    'Predict Now',
    'PLEASE SEND EXACTLY',
    'SCAN TO SEND',
    'PayStack Payment',
    'Stripe Payment',
    'Please Pay',
    'To Get',
    'Pay Now',
    'Charge',
    'Rate',
    'Payable Amount',
    'Payment Preview',
    'Conversion Rate',
    'In',
    'Payable',
    'Conversion with',
    'and final value will Show on next step',
    'SL',
    'Details',
    'Remaining Balance',
    'Time',
    'Select',
    'Select image',
    'First Name',
    'Last Name',
    'Username',
    'City',
    'Zip Code',
    'Address',
    'Submit',
    'Current Password',
    'New Password',
    'Re Password',
    'Event',
    'Question',
    'Threat',
    'Predict Amount',
    'Return Amount',
    'Result',
    'Win',
    'Lose',
    'Refunded',
    'Processing',
    'Pending',
    'Success',
    'Rejected',
    'No Data Found!',
    'Fill up below the instruction',
    'Limit',
    'Email Address',
    'Password',
    'Your Account has been Suspended',
    'E-mail Verification',
    'Your E-mail',
    'Enter Code',
    'SMS Verification',
    'Your Contact Number',
    'Trx',
    'Payment Gateway',
    'Status',
    'Withdraw Money DeActive By Admin',
    'Withdraw Now',
    'Confirm',
    'Withdraw Limit',
    'Withdraw Via',
    'Recipient Get Amount in',
    'Additional Information To Withdraw Confirm',
    'Confirm Now',
    'Make Deposit Request Via Payment Method',
    'Enter Amount',
    'Deposit Limit',
    'Deposit Charge',
    'Please follow the instruction below',
    'You have requested to deposit',
    'Please pay',
    'for successful payment',
    'Delay',
    'Change',
    'Remove',
    'Unauthorized',
    'Back Home',
    'Page Not Found',
    'Contact Number',
    'E-mail Address',
    'Repeat Password',
    'Send Successfully',
    'Authentication',
    'You can resend Verification Code after',
    'minutes',
    'Verification Code Send successfully',
    'Your Profile has been verified successfully',
    'Verification Code Did not matched.',
    'Password Changes Successfully.',
    'Current Password Not Match',
    'Profile Updated Successfully.',
    'Balance Transfer',
    'This Email could not Found!',
    'You could not Transfer in your account!',
    'Invalid User!',
    'Minimum Transfer Amount',
    'Maximum Transfer Amount',
    'Balance Transfer  has been Successful',
    'Password Do Not Match',
    'Insufficient Balance',
    'Successfully Prediction in',
    'Minimum Amount',
    'Time has been expired',
    'Your Prediction limit over in',
    'You can next predict after',
    'seconds in',
    'Minimum Withdraw Amount',
    'Maximum Withdraw Amount',
    'Withdraw Form',
    'Withdraw request Successfully Submitted. Wait For Confirmation.',
);
